name: Deploy

on:
  push:
    branches: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest

  update-VPS-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Update image inside VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PORT: ${{ secrets.VPS_PORT }}
          KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            docker stop $(docker ps -a -q --filter ancestor=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }})
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}
            docker run -e MONGO_DB_HOST='${{ secrets.MONGO_DB_HOST }}' -e MONGO_DB_NAME='${{ secrets.MONGO_DB_NAME }}' -e MONGO_DB_PASSWORD='${{ secrets.MONGO_DB_PASSWORD }}' -e MONGO_DB_HOST='${{ secrets.MONGO_DB_HOST }}' -e MONGO_DB_PORT=${{ secrets.MONGO_DB_PORT }} -d -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}
            docker container prune --force
            docker image prune --all --force
